### ISSUE TITLE
Duplicate `BackendRefs` in `HTTPRoute` rules

### ISSUE THREAD

**Issue by mlavacca** [kubernetes-sigs/ingress2gateway#102]
**What happened**:

When converting Ingresses with the same rules into Gateway API objects, `HTTPRoute` Matches are properly grouped, while rule `BackendRefs` are duplicated.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

the conversion output of the following yaml file: 
```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingressa
  namespace: migration
  annotations:
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /mia
        pathType: Prefix
        backend:
          service:
            name: mia
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingressb
  namespace: migration
  annotations:
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /mia
        pathType: Prefix
        backend:
          service:
            name: mia
            port:
              number: 80
```
is
```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  creationTimestamp: null
  name: kong
  namespace: migration
spec:
  gatewayClassName: kong
  listeners:
  - name: http
    port: 80
    protocol: HTTP
status: {}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  creationTimestamp: null
  name: ingressA-all-hosts
  namespace: migration
spec:
  parentRefs:
  - name: kong
  rules:
  - backendRefs:
    - name: mia
      port: 80
    - name: mia
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /mia
status:
  parents: []
```

**Anything else we need to know?**:

**Comment by pottekkat** [comment]
@LiorLieberman Can I take up this issue? I haven't contributed to the Gateway API before, but I want to get involved, and this might be a good place to start.

**Comment by LiorLieberman** [comment]
Hey @pottekkat, would be great to have you!

I think it is an awesome place to start. 
Lets double check that @mlavacca was not already doing it. 

@mlavacca are you good with @pottekkat taking this? if yes - assign it to them.

**Comment by mlavacca** [comment]
Hi @pottekkat, it's great to have you on this one! 

/assign @pottekkat

**Comment by LiorLieberman** [comment]
Thanks @mlavacca. 

@pottekkat let us know if you need any help!

**Comment by LiorLieberman** [comment]
Thanks @pottekkat. We are waiting on a few more changes to get in first.

**Comment by pottekkat** [comment]
There seems to be another bug here. Both the Gateway and the HTTPRoute resource seem to be duplicated in the output. Is it expected? The test yaml is the one shared in the issue.

```
./ingress2gateway print -A --input_file ./test-ingress.yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  creationTimestamp: null
  name: kong
  namespace: migration
spec:
  gatewayClassName: kong
  listeners:
  - name: http
    port: 80
    protocol: HTTP
status: {}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  creationTimestamp: null
  name: kong
  namespace: migration
spec:
  gatewayClassName: kong
  listeners:
  - name: http
    port: 80
    protocol: HTTP
status: {}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  creationTimestamp: null
  name: ingressa-all-hosts
  namespace: migration
spec:
  parentRefs:
  - name: kong
  rules:
  - backendRefs:
    - name: mia
      port: 80
    - name: mia
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /mia
status:
  parents: []
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  creationTimestamp: null
  name: ingressa-all-hosts
  namespace: migration
spec:
  parentRefs:
  - name: kong
  rules:
  - backendRefs:
    - name: mia
      port: 80
    - name: mia
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /mia
status:
  parents: []
```
