### ISSUE TITLE
--input_file requires an available cluster, does not support yaml files with multiple resources, does not give errors

### ISSUE THREAD

**Issue by simonfelding** [kubernetes-sigs/ingress2gateway#122]
**What happened**:
I wanted to convert ingresses in a multi-yaml file usin --input_file, without access to the cluster.

`./ingress2gateway print --input_file harbor.yaml`
resulted in
`Error: failed to create client: Get "http://localhost:6443/api?timeout=32s": dial tcp 127.0.0.1:6443: connect: connection refused`

because the cluster is airgapped and unavailable for my laptop. With connection to the cluster, it returns
`No resources found in default namespace`.

**What you expected to happen**:
ingress yamls are converted to httproutes.

**How to reproduce it (as minimally and precisely as possible)**:
`helm template harbor oci://registry-1.docker.io/bitnamicharts/harbor --set exposureType=ingress -set ingress.core.ingressClassName=nginx -n harbor > harbor.yaml`

`./ingress2gateway print --input_file harbor.yaml`

the above gives no meaningful output, but should either give an error or the expected output.

**Comment by simonfelding** [comment]
related to https://github.com/kubernetes-sigs/ingress2gateway/pull/78

**Comment by dpasiukevich** [comment]
Should be fixed by https://github.com/kubernetes-sigs/ingress2gateway/pull/128

Now for reading local files the k8sclient creation is skipped.

**Comment by LiorLieberman** [comment]
@simonfelding I believe this issue is fixed now.
Can you confirm?

**Comment by LiorLieberman** [comment]
closing this as fixed. Feel free to reopen if needed.

**Comment by davinkevin** [comment]
@LiorLieberman I have still this error with 0.2.0: 

<img width="426" alt="image" src="https://github.com/kubernetes-sigs/ingress2gateway/assets/1970922/d6e42ef7-f30a-4b8e-96fe-9031c9baad69">

My only wish is to use the cli offline, on our `gitops` repository

**Comment by levikobi** [comment]
Hi @davinkevin, I guess the resources in your `ingress.yaml` file do not specify a namespace (and if they do, it isn't the default one). Please use -A (--all-namespaces) flag

**Comment by davinkevin** [comment]
Thank you for your answer @levikobi . Result is different but not really better.

<img width="871" alt="image" src="https://github.com/kubernetes-sigs/ingress2gateway/assets/1970922/3f9a61ff-eefb-4f8b-b727-b14e8412d06a">

My file is just this: 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podinfo.ingress.k8s.local
spec:
  rules:
    - host: podinfo.ingress.k8s.local
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: podinfo
                port:
                  name: http
```

**Comment by levikobi** [comment]
@davinkevin are you sure you're using release 0.2?
I can't seem to reproduce the error you're showing here TBH.. Neither on main

**Comment by davinkevin** [comment]
<img width="1152" alt="image" src="https://github.com/kubernetes-sigs/ingress2gateway/assets/1970922/8a295032-ced0-47d7-b7b1-d13d51258778">

I would say yes 🤔

**Comment by LiorLieberman** [comment]
Hey @davinkevin the reason is that you did not specify `ingressClassName` in spec. So no provider pick it up. 

Also, I think there is a bug when using `port.name`. Can you try to add `ingressClassName` and change `port.name` to `port.number` and report back if it works?

**Comment by davinkevin** [comment]
Hello @LiorLieberman,

So, I've first tried with a specific `ingressClassName` and the change you mentioned:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podinfo.ingress.k8s.local
spec:
  ingressClassName: nginx
  rules:
    - host: podinfo.ingress.k8s.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: podinfo
                port:
                  number: 1234
```

And it's working! The result is: 

```
ingress2gateway print --input_file=ingress.yaml --providers=ingress-nginx -A
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  creationTimestamp: null
  name: nginx
spec:
  gatewayClassName: nginx
  listeners:
  - hostname: podinfo.ingress.k8s.local
    name: podinfo-ingress-k8s-local-http
    port: 80
    protocol: HTTP
status: {}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  creationTimestamp: null
  name: podinfo.ingress.k8s.local-podinfo-ingress-k8s-local
spec:
  hostnames:
  - podinfo.ingress.k8s.local
  parentRefs:
  - name: nginx
  rules:
  - backendRefs:
    - name: podinfo
      port: 1234
    matches:
    - path:
        type: PathPrefix
        value: /
status:
  parents: []
```

If I use the named port, I indeed have an error:

<img width="957" alt="image" src="https://github.com/kubernetes-sigs/ingress2gateway/assets/1970922/c233e34b-8bb8-4406-bbfe-73826dafda37">

So, the main remark I could do is, for newcomers, it's really a shame to not be able to use the tool on bare `ingress` files. 
Maybe a `generic` provider to manage ingress if all others didn't pick anything?
