### ISSUE TITLE
Support Gateway API extensions (output providers)

### ISSUE THREAD

**Issue by arkodg** [kubernetes-sigs/ingress2gateway#125]
**What would you like to be added**:

Add the ability to translate `provider` specific APIs into implementation specific Gateway API extensions (output providers) for fields not currently supported in the Gateway API

**Why this is needed**:
Adding ability to translate all input provider specific intent without losing any functionality
For e.g. the current [ingress-nginx](https://github.com/kubernetes-sigs/ingress2gateway/blob/main/pkg/i2gw/providers/ingressnginx/README.md#ingress-nginx-provider) translation only translates a subset of the API (annotations)  https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#annotations 
Without this feature, its unlikely that the user will migrate to Gateway API until all the input provider features are supported in the Gateway API APIs
If this tool supports the notion of output providers, the input API could be translated to various implementation specific Gateway API extensions

**Comment by mlavacca** [comment]
Hi @arkodg , thanks for creating this issue! It looks reasonable to me 👍

**Comment by arkodg** [comment]
cool, I think `istio` is a good one to start off with and a use case would be to translate existing Istio resources in native istio type to Gateway API + Gateway API extensions defined in istio
we probably need an explicit flag ( e.g. `--out-provider=istio`) to opt into this
does this sgty @LiorLieberman @howardjohn ?

**Comment by arkodg** [comment]
@LiorLieberman here's a example for Istio

Input
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: my-gateway
  namespace: test
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - test.com
  - port:
      number: 443
      protocol: HTTPS
    hosts:
    - "bookinfo/*.bookinfo.com"
    -  "*"
    tls:
      httpsRedirect: true
      mode: SIMPLE
      # all following tls related fields are ignored as there's no direct mapping to the k8s gateway api
      serverCertificate: /etc/certs/servercert.pem
      privateKey: /etc/certs/privatekey.pem
      credentialName: bookinfo-secret
      caCertificates: /etc/certs/caCertificates
      subjectAltNames: ["v1"]
      verifyCertificateSpki: ["v1"]
      verifyCertificateHash: ["v1"]
      minProtocolVersion: TLSV1_0
      maxProtocolVersion: TLSV1_3
      cipherSuites: ["v1"]
    bind: 1.2.3.4 # is ignored
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: allow-nothing
 namespace: test
spec:
 selector:
   matchLabels:
     app: istio-ingressgateway
     istio: ingressgateway   
```

Output
```
piVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: my-gateway
  namespace: test
spec:
  gatewayClassName: istio
  listeners:
  - name: https-protocol-bookinfo-ns-wildcard.bookinfo.com
    hostname: "*.bookinfo.com"
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
 ---
 apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: allow-nothing
 namespace: test
spec:
  targetRef:
    kind: Gateway
    group: gateway.networking.k8s.io
    name:  my-gateway  
```

**Comment by mlavacca** [comment]
> @LiorLieberman here's an example for Istio
> 
> Input
> 
> ```
> apiVersion: networking.istio.io/v1beta1
> kind: Gateway
> metadata:
>   name: my-gateway
>   namespace: test
> spec:
>   selector:
>     app: istio-ingressgateway
>     istio: ingressgateway
>   servers:
>   - port:
>       number: 80
>       name: http
>       protocol: HTTP
>     hosts:
>     - test.com
>   - port:
>       number: 443
>       protocol: HTTPS
>     hosts:
>     - "bookinfo/*.bookinfo.com"
>     -  "*"
>     tls:
>       httpsRedirect: true
>       mode: SIMPLE
>       # all following tls related fields are ignored as there's no direct mapping to the k8s gateway api
>       serverCertificate: /etc/certs/servercert.pem
>       privateKey: /etc/certs/privatekey.pem
>       credentialName: bookinfo-secret
>       caCertificates: /etc/certs/caCertificates
>       subjectAltNames: ["v1"]
>       verifyCertificateSpki: ["v1"]
>       verifyCertificateHash: ["v1"]
>       minProtocolVersion: TLSV1_0
>       maxProtocolVersion: TLSV1_3
>       cipherSuites: ["v1"]
>     bind: 1.2.3.4 # is ignored
> ---
> apiVersion: security.istio.io/v1beta1
> kind: AuthorizationPolicy
> metadata:
>  name: allow-nothing
>  namespace: test
> spec:
>  selector:
>    matchLabels:
>      app: istio-ingressgateway
>      istio: ingressgateway   
> ```
> 
> Output
> 
> ```
> piVersion: gateway.networking.k8s.io/v1
> kind: Gateway
> metadata:
>   name: my-gateway
>   namespace: test
> spec:
>   gatewayClassName: istio
>   listeners:
>   - name: https-protocol-bookinfo-ns-wildcard.bookinfo.com
>     hostname: "*.bookinfo.com"
>     port: 443
>     protocol: HTTPS
>     tls:
>       mode: Terminate
>  ---
>  apiVersion: security.istio.io/v1beta1
> kind: AuthorizationPolicy
> metadata:
>  name: allow-nothing
>  namespace: test
> spec:
>   targetRef:
>     kind: Gateway
>     group: gateway.networking.k8s.io
>     name:  my-gateway  
> ```

I think this use case can be addressed by https://github.com/kubernetes-sigs/ingress2gateway/pull/78, but only when reading from files. With it, it will be possible to output all the input resources that do not belong to the set of converted resources. When it comes to reading resources from a cluster, that flag cannot be used as it is now in the PR.

**Comment by LiorLieberman** [comment]
@sawsa307 as discussed before, support for input and output providers is necessary to close this issue.

**Comment by sawsa307** [comment]
Yes I think #188 merge automatically triggered this since it said `Fixes #125`, I'll use a different description next time to tag this issue.

**Comment by gcasella** [comment]
I would like to make a suggestion here as well. 
Instead of the output providing both `kind: Gateway` and `kind: HTTPRoute` I would suggest giving the option to only export the Gateway resource or HTTPRoute resource. 


This would be useful if users are using a shared listener for example:
```
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: development-gateway
  namespace: sample-namespace
  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  infrastructure:
    annotations:
      lbipam.cilium.io/ips: 3.3.3.3
  gatewayClassName: cilium
  listeners:
    - name: https
      hostname: "*.example.com"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: wildcard-example.com-tls
```


In my use-case, i have multiple ingress-nginx resources defined, what would be nice is to migrate just the HTTPRoutes to use the Kubernetes GatewayAPI

These are just my two cents.
