### ISSUE TITLE
Psudo Ingress Controller

### ISSUE THREAD

**Issue by kfox1111** [kubernetes-sigs/ingress2gateway#130]
Are there any plans to support running ingress2gateway as a controller that watches for ingress objects and uploads the result as gateway objects directly to the cluster? This would help smooth out the transition to the gateway api?

**Comment by LiorLieberman** [comment]
That is a very interesting direction to go. 
@mlavacca also talked with me about it 3 months back. 

My few concerns/thoughts are: 
- The current ingress2gateway tool is operating as "Best Effort".  And it is very much depends on the support level or the conversion logic the provider (an implementation) added. In this case, the controller can not just auto apply the gateway objects, a human intervention is needed to confirm and add the missing parts.

- Ideally we want users to move to use Gateway API and discourage using Ingress. 
Developing a controller that watches for Ingress resources, convert them, and apply to the cluster might:
        a) Discourage people from learning/moving to apply Gateway API resources (as the controller does the job for them)
        b) Causes a situation where the stored objects (lets say in git) are ingresses, but in the cluster there are other objects
        c) Requires vast development and collaborative maintenance from different implementations. 
       

That said, those are just initial thoughts. I am definitely up to be convinced otherwise.

**Comment by kfox1111** [comment]
Yeah, I can understand the concern around such functionality slowing down adoption of the Gateway API, but in my case, I think it might help speed it up by breaking the deadlock around it.

An example situation...

Some cluster admins have been running ingress-nginx for a very long time. It does not currently have gateway api support, and seems unlikely to get support any time soon.

There are Gateway API only implementations such as envoy gateway that may be desirable to switch to.

There are also a ton of existing helm charts that currently only support the ingress api. It is difficult to get them to add the new apis unless there are enough users asking for support.

In environments like this, ingress2gateway as a controller can bridge the gap. Allow cluster admins to adopt a native gateway api only controller but have a bridge to support all the existing charts. Then the helm chart users have an easier path to request from the helm chart devs, "We'd like official gateway support for the chart. The software does work with the gateway api as we're already using it." The users have a harder time doing that when the clusters they are running on doesn't have support yet. The chart devs have an easier time adopting the gateway api if someone else has already ensured it works, and know more and more end clusters are gateway api enabled.

ingress2controller as a standalone command works well for static manifests, but not as well for helm based deployments. Especially when pipelines are involved.

**Comment by phoenix-frozen** [comment]
Sorry for the thread necromancy, but the "I have too many helm charts that generate ingresses" is a substantial pain point. Please _please_ reconsider this FR

**Comment by kfox1111** [comment]
Yes please. can we reopen this?

**Comment by Stevenjin8** [comment]
@kfox1111 I'm not completely against the idea of having this as a controller, but have many many concerns.

For one, I agree with @LiorLieberman that the conversion is best effort and, generally speaking, cannot be correct. For example, we will not generate a self-signed TLS cert on port 443, or not verify backend TLS certs. There are probably a bunch of other examples around TLS. We also don't allow referencing TLS capture groups. 

So the question becomes what should we do if we cannot do a perfect conversion. Given that this is applying to an ingress controller, there is very little room for failure. If we were to "fail" when we cannot do a "proper" conversion, I'd much rather do that in a CI/CD pipeline than in a live cluster.

Having it be a controller also makes project maintenance a lot harder. Backcompatibility becomes a crucial concern and things that used to become bugs become security vulns. **There has been a surge in interest in this project given the Ingress NGINX retirement, but its not clear whether that support will continue and I worry that we would be putting in the same position as Ingress NGINX**.

I'm also curious if the conversation around Ingress NGINX migration has changed given the retirement. When you say

> There are also a ton of existing helm charts that currently only support the ingress api. It is difficult to get them to add the new apis unless there are enough users asking for support.

do you mean open source projects or organizations just tend to have a lot of Ingress resources? Are these Ingress resources vanilla Ingresses, or do they have a bunch of Ingress NGINX annotations.

In my mind, I could be convinced to support vanilla and maybe a VERY small subset of Ingress NGINX resources, but I think that the set of supported annotations would be too small to be generally useful.

**Comment by kfox1111** [comment]
go to artifacthub.io, pick a random chart, and compare its ingress support vs gateway support. Very few support gateway that do support ingress

I think the concern around the ingress-nginx deprecation has been so strong because its so commonly used and there is no good path from ingress-nginx to gateway api at the moment. Annotations are a real must to do a lot of services/sites from my experience. we see commonly between a dozen or 2 annotations used on a lot of deployments.

I think it would be interesting to give an ingress controller like ingress2gateway option for a time bound period. like, 18 months from ingress-nginx support stops. This allows a migration path without leaving a lot of users to scramble on what to do. It could support some of the most common ingress-nginx annotations rather then be as generic to ease the pain, but also being timebound, it doesnt put an indefinite support burden on folks either.

\

**Comment by phoenix-frozen** [comment]
> do you mean open source projects or organizations just tend to have a lot of Ingress resources? Are these Ingress resources vanilla Ingresses, or do they have a bunch of Ingress NGINX annotations.

It is a very common pattern for a helm chart to have, in its `values.yaml`, a field (or subfield) called `ingress`, which it consumes to generate an Ingress resource for the service it's installing. This field generally contains the minimum configuration necessary:
* host/path rules
* tls config
* Ingress class
* most importantly: annotations

The point here is that helm charts do not, in general, generate annotations. They generate vanilla Ingress resources with annotations provided by the helm chart user.

The point here would be: switching from (say) ingress-nginx to ingress2gateway _as an ingress controller_ is still a migration. But it places the migration in the hands of the user, rather than the helm chart author.

> ... I think that the set of supported annotations would be too small to be generally useful.

Frankly, I think supporting other people's annotations -- really any annotations outside of the `kubernetes.io` namespace -- would be a huge mistake. The point is to support the creation of ingress resources, and maybe have some custom annotations for stuff you need to pass through to the backing (say) `HTTPRoute` controller.

Maybe you even say that any annotations are passed through to the resulting `HTTPRoute` object unmodified. The point is not that people who use helm charts shouldn't _know_ they're actually using the Gateway API. The point is to hand them tools to not need to modify their helm charts to get them to work in the new world.

**Comment by phoenix-frozen** [comment]
To follow up with an example, look at the helm chart for Headlamp. It has an `ingress` field, in which I have the following:

```yaml
ingress:
  enabled: true
  ingressClassName: "nginx-internal"
  annotations:
    cert-manager.io/cluster-issuer: freeipa-acme-issuer-internal
  hosts:
  - host: headlamp.nzprh.twilightparadox.com
    paths:
    - path: /
      type: Prefix
  tls:
  - secretName: headlamp-tls
    hosts:
    - headlamp.nzprh.twilightparadox.com
```

That generates the following Ingress:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: freeipa-acme-issuer-internal
    meta.helm.sh/release-name: headlamp
    meta.helm.sh/release-namespace: headlamp
  labels:
    app.kubernetes.io/instance: headlamp
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/version: 0.40.0
    helm.sh/chart: headlamp-0.40.0
    helm.toolkit.fluxcd.io/name: headlamp
    helm.toolkit.fluxcd.io/namespace: headlamp
  name: headlamp
  namespace: headlamp
spec:
  ingressClassName: nginx-internal
  rules:
  - host: headlamp.nzprh.twilightparadox.com
    http:
      paths:
      - backend:
          service:
            name: headlamp
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - headlamp.nzprh.twilightparadox.com
    secretName: headlamp-tls
```

Frankly, it's an entirely vanilla affair. But the thing to note is: the annotations are all mine, except for some boring Helm stuff that you don't need to care about. So an Ingress-to-HTTPRoute controller would "just" need to generate an `HTTPRoute` with equivalent configuration. I think this is not quite specified enough: the ingressClassName would have to say `ingress2gateway`, so you probably need a custom annotation along the lines of `ingress2gateway.kubernetes.io/parentRefs` to fill in the remaining blanks.

In fact, the one I actually use here, the `cert-manager` one, shouldn't even be passed through to the `HTTPRoute`; it should just be left on the Ingress, and only the TLS configuration in the body of the Ingress resource should be passed through.

EDIT: formatting and clarity

**Comment by phoenix-frozen** [comment]
Maybe a second example: the Docker Registry chart. Same basic idea, but it's more complicated:

```yaml
ingress:
  enabled: true
  className: nginx-internal
  hosts:
  - registry.nzprh.twilightparadox.com
  annotations:
    cert-manager.io/cluster-issuer: freeipa-acme-issuer-internal
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://registry-ui.nzprh.twilightparadox.com"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "false"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Accept"
  tls:
  - secretName: registry-tls
    hosts:
    - registry.nzprh.twilightparadox.com
```

which generates the following

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: freeipa-acme-issuer-internal
    meta.helm.sh/release-name: registry
    meta.helm.sh/release-namespace: registry
    nginx.ingress.kubernetes.io/cors-allow-credentials: "false"
    nginx.ingress.kubernetes.io/cors-allow-headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Accept
    nginx.ingress.kubernetes.io/cors-allow-methods: GET, PUT, POST, DELETE, PATCH,
      OPTIONS
    nginx.ingress.kubernetes.io/cors-allow-origin: https://registry-ui.nzprh.twilightparadox.com
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  labels:
    app: docker-registry
    app.kubernetes.io/managed-by: Helm
    chart: docker-registry-3.0.0
    helm.toolkit.fluxcd.io/name: registry
    helm.toolkit.fluxcd.io/namespace: registry
    heritage: Helm
    release: registry
  name: registry-docker-registry
  namespace: registry
spec:
  ingressClassName: nginx-internal
  rules:
  - host: registry.nzprh.twilightparadox.com
    http:
      paths:
      - backend:
          service:
            name: registry-docker-registry
            port:
              number: 5000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - registry.nzprh.twilightparadox.com
    secretName: registry-tls
```

Once again, the annotations are either mine or pretty boring. Of the ones that are mine, the `cert-manager` one requires no action, but the `ingress-nginx` ones might. Maybe this is naive, but: the thing I'm driving at is that no-one should be asking you to attempt to support those annotations _unmodified_. But, since it looks like CORS support is [proposed](https://gateway-api.sigs.k8s.io/geps/gep-1767/) as an `HTTPRoute` field, you might want to define a custom set of annotations for filling in that field. And maybe in some implementations this is done through annotations, so you probably do need a scheme for passing those through. (But notably not a catchall, since the cert-manager one should be left where it is.)

Does all of that make sense?

EDIT: formatting and clarity
