### ISSUE TITLE
Unnecessary panic calls causes unclear errors 

### ISSUE THREAD

**Issue by LiorLieberman** [kubernetes-sigs/ingress2gateway#151]
**What happened**:
We have few places in the codebase where we call panic for no good reason.
For example, When we get calculation errors [here](https://github.com/kubernetes-sigs/ingress2gateway/blob/main/pkg/i2gw/providers/ingressnginx/canary.go#L44-L45) we never see them and panic is called. 

**What you expected to happen**:
We should not call panic
**How to reproduce it (as minimally and precisely as possible)**:
One example would be to run the tool on an ingress with `port.name` (which is unsupported)
Pasting an ingress.yaml example for simplicity:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podinfo.ingress.k8s.local
spec:
  ingressClassName: kong
  rules:
    - host: podinfo.ingress.k8s.local
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: podinfo
                port:
                  name: http
```

**Anything else we need to know?**:
Seems all occurrences were copy pasted from the original code in https://github.com/kubernetes-sigs/ingress2gateway/pull/40.

/assign @levikobi
