### ISSUE TITLE
istio: invalid convert result

### ISSUE THREAD

**Issue by zirain** [kubernetes-sigs/ingress2gateway#154]
**What happened**:

try to convert following configuration to istio, but rejected by apiserver

**What you expected to happen**:

apiserver didn't reject the converted result.

**How to reproduce it (as minimally and precisely as possible)**:

apply following result to cluster:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
    - "*"
  gateways:
    - httpbin-gateway
  http:
    - match:
        - uri:
            prefix: /get
        - uri:
            regex: ^/status/[0-9]{3}$
      route:
        - destination:
            host: httpbin
            port:
              number: 8080
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: httpbin
            port:
              number: 8080
```

then running:
```console
ingress2gateway print --providers istio | k apply -f -
I0419 16:42:17.535135   38688 converter.go:148] ignoring field: istio.Gateway[httpbin-gateway].Server[0].Port.Name
gateway.gateway.networking.k8s.io/httpbin-gateway configured
Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"gateway.networking.k8s.io/v1\",\"kind\":\"HTTPRoute\",\"metadata\":{\"annotations\":{},\"creationTimestamp\":null,\"name\":\"httpbin-idx-0\",\"namespace\":\"default\"},\"spec\":{\"hostnames\":[\"*\"],\"parentRefs\":[{\"group\":\"gateway.networking.k8s.io\",\"kind\":\"Gateway\",\"name\":\"httpbin-gateway\"}],\"rules\":[{\"backendRefs\":[{\"name\":\"httpbin\",\"namespace\":\"default\",\"port\":8080,\"weight\":0}],\"matches\":[{\"path\":{\"type\":\"PathPrefix\",\"value\":\"/get\"}},{\"path\":{\"type\":\"RegularExpression\",\"value\":\"^/status/[0-9]{3}$\"}}]}]},\"status\":{\"parents\":null}}\n"}},"spec":{"hostnames":["*"],"rules":[{"backendRefs":[{"name":"httpbin","namespace":"default","port":8080,"weight":0}],"matches":[{"path":{"type":"PathPrefix","value":"/get"}},{"path":{"type":"RegularExpression","value":"^/status/[0-9]{3}$"}}]}]}}
to:
Resource: "gateway.networking.k8s.io/v1, Resource=httproutes", GroupVersionKind: "gateway.networking.k8s.io/v1, Kind=HTTPRoute"
Name: "httpbin-idx-0", Namespace: "default"
for: "STDIN": error when patching "STDIN": HTTPRoute.gateway.networking.k8s.io "httpbin-idx-0" is invalid: spec.hostnames[0]: Invalid value: "*": spec.hostnames[0] in body should match '^(\*\.)?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$'
Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"gateway.networking.k8s.io/v1\",\"kind\":\"HTTPRoute\",\"metadata\":{\"annotations\":{},\"creationTimestamp\":null,\"name\":\"httpbin-idx-1\",\"namespace\":\"default\"},\"spec\":{\"hostnames\":[\"*\"],\"parentRefs\":[{\"group\":\"gateway.networking.k8s.io\",\"kind\":\"Gateway\",\"name\":\"httpbin-gateway\"}],\"rules\":[{\"backendRefs\":[{\"name\":\"httpbin\",\"namespace\":\"default\",\"port\":8080,\"weight\":0}],\"matches\":[{\"path\":{\"type\":\"PathPrefix\",\"value\":\"/\"}}]}]},\"status\":{\"parents\":null}}\n"}},"spec":{"hostnames":["*"],"rules":[{"backendRefs":[{"name":"httpbin","namespace":"default","port":8080,"weight":0}],"matches":[{"path":{"type":"PathPrefix","value":"/"}}]}]}}
to:
Resource: "gateway.networking.k8s.io/v1, Resource=httproutes", GroupVersionKind: "gateway.networking.k8s.io/v1, Kind=HTTPRoute"
Name: "httpbin-idx-1", Namespace: "default"
for: "STDIN": error when patching "STDIN": HTTPRoute.gateway.networking.k8s.io "httpbin-idx-1" is invalid: spec.hostnames[0]: Invalid value: "*": spec.hostnames[0] in body should match '^(\*\.)?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$'
```

**Anything else we need to know?**:
