### ISSUE TITLE
Convention of Ingress with multiple rules generates incorrect results

### ISSUE THREAD

**Issue by czczycz** [kubernetes-sigs/ingress2gateway#174]
**What happened**:
I try to convert the ingress resource from single file using Ingress2Gateway v0.3.0-rc1, but the generated HTTPRoute is incorrect. 
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  creationTimestamp: null
  name: example-ingress-foo-example-com
spec:
  hostnames:
  - foo.example.com
  parentRefs:
  - name: nginx
  rules:
  - backendRefs:
    - name: foo-app
      port: 80
    - name: foo-orders-app
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /
  - backendRefs:
    - name: foo-orders-app
      port: 80
    - name: foo-app
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /orders
status:
  parents: []
```

Please see `How to reproduce it` below

**What you expected to happen**:
The correct result should be:

```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: foo
spec:
  parentRefs:
  - name: example-gateway
    sectionName: https
  hostnames:
  - foo.example.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: foo-app
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /orders
    backendRefs:
    - name: foo-orders-app
      port: 80
```

**How to reproduce it (as minimally and precisely as possible)**:
Here's my ingress resource, it's just an example from Gateway API doc [https://gateway-api.sigs.k8s.io/guides/migrating-from-ingress/#example](url)
In order to use Ingress2Gateway, I have to change the value of ingressClassName to nginx and delete annotion `some-ingress-controller.example.org/tls-redirect`.
After convention, The HTTPRoute `example-ingress-foo-example-com` has two backendRefs

The command is
`ingress2gateway print --input-file ingress.yaml -A --providers ingress-nginx`

```apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - foo.example.com
    - bar.example.com
    secretName: example-com
  rules:
  - host: foo.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: foo-app
            port:
              number: 80
      - path: /orders
        pathType: Prefix
        backend:
          service:
            name: foo-orders-app
            port:
              number: 80
  - host: bar.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bar-app
            port:
              number: 80
```
**Anything else we need to know?**:
