### ISSUE TITLE
Error for named ports

### ISSUE THREAD

**Issue by gebinic** [kubernetes-sigs/ingress2gateway#209]
**What happened**:

I executed `./ingress2gateway print --providers ingress-nginx` and got an error:

```
# Encountered 3 errors # paths.backends[0].service.port: Invalid value: "name": named ports not supported: http # paths.backends[0].service.port: Invalid value: "name": named ports not supported: http # paths.backends[0].service.port: Invalid value: "name": named ports not supported: http
```

**What you expected to happen**:

I expected a successful conversion from Ingress to Gateway.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy an nginx and an application with a named port in your k8s cluster.

**Comment by LiorLieberman** [comment]
Thanks @gebinic 

Can you please paste your input (meaning ingresses in the cluster you are trying to convert)?

The tool does not support named ports now, but wanted to see your input to provide a more tailored response
Thanks,

**Comment by gebinic** [comment]
Ingress:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: my-app
    meta.helm.sh/release-namespace: my-namespace
  labels:
    app: spring
    app.kubernetes.io/managed-by: Helm
    chart: spring-2.1.2
    group: app-ingress
    heritage: Helm
    release: my-app
  name: my-app
  namespace: my-namespace
spec:
  rules:
  - host: myHost.com
    http:
      paths:
      - backend:
          service:
            name: my-app
            port:
              name: http
        path: /my-app
        pathType: Prefix
  tls:
  - hosts:
    - myHost.com
    secretName: my-tls-secrets
```

Service:

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: my-app
    meta.helm.sh/release-namespace: my-namespace
  labels:
    app: spring
    app.kubernetes.io/managed-by: Helm
    chart: spring-2.1.2
    heritage: Helm
    release: my-app
  name: my-app
  namespace: my-namespace
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: grpc
    port: 8090
    protocol: TCP
    targetPort: 8090
  - name: management
    port: 8558
    protocol: TCP
    targetPort: 8558
  selector:
    app: my-app
  type: ClusterIP
```
