### ISSUE TITLE
ingress2gateway assumes ingressClass

### ISSUE THREAD

**Issue by adrianmoisey** [kubernetes-sigs/ingress2gateway#214]
**What happened**:

ingress2nginx assumed that for an ingress-nginx Ingress, the class name had to be `nginx`.

ie, this works:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /testpath
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 80
```

This doesn't work:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: ingress-nginx
  rules:
  - http:
      paths:
      - path: /testpath
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 80
```

**What you expected to happen**:

I don't expect ingress2nginx to assume a certain class name, especially when pointing ingress2nginx it at a file.

**How to reproduce it (as minimally and precisely as possible)**:

Write the "doesn't work" example to a file, and run:
`ingress2gateway print --providers=ingress-nginx --input-file thatfile.yaml`

**Anything else we need to know?**:
