### ISSUE TITLE
Add support for GCE ingress class/provider

### ISSUE THREAD

**Issue by bokjo** [kubernetes-sigs/ingress2gateway#87]
**What would you like to be added**: support for the GCE ingress provider

**Why this is needed**: to convert existing GCE ingress to the new GW API

Error while executing 
```sh
ingress2gateway print
I1026 10:58:24.119436   48466 request.go:682] Waited for 1.049636692s due to client-side throttling, not priority and fairness, request: GET:https://XX.XX.XX.XX/apis/elasticsearch.k8s.elastic.co/v1beta1?timeout=32s
Error:


# Encountered 2 errors # spec.rules[0].http.paths[0].pathType: Invalid value: "ImplementationSpecific": unsupported path match type: ImplementationSpecific # spec.rules[0].http.paths[0].pathType: Invalid value: "ImplementationSpecific": unsupported path match type: ImplementationSpecific
Usage:
  ingress2gateway print [flags]

Flags:
  -A, --all-namespaces      If present, list the requested object(s) across all namespaces. Namespace in current context is ignored even
                            if specified with --namespace.
  -h, --help                help for print
      --input_file string   Path to the manifest file. When set, the tool will read ingresses from the file instead of reading from the cluster. Supported files are yaml and json
  -n, --namespace string    If present, the namespace scope for this CLI request
  -o, --output string       Output format. One of: (json, yaml) (default "yaml")
      --providers strings   If present, the tool will try to convert only resources related to the specified providers, supported values are [ingress-nginx kong] (default [ingress-nginx,kong])
```

the current ingress has the following YAML (Redacted info)

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.gcp.kubernetes.io/pre-shared-cert: mcrt-XXX,mcrt-YYY,mcrt-ZZZ
    ingress.kubernetes.io/backends: '{"k8s1-XXX":"HEALTHY"}'
    ingress.kubernetes.io/forwarding-rule: k8s2-fr-XXX
    ingress.kubernetes.io/https-forwarding-rule: k8s2-fs-XXX
    ingress.kubernetes.io/https-target-proxy: k8s2-ts-XXX
    ingress.kubernetes.io/redirect-url-map: k8s2-rm-XXX
    ingress.kubernetes.io/ssl-cert: mcrt-XXX,mcrt-YYY,mcrt-ZZZ
    ingress.kubernetes.io/target-proxy: k8s2-tp-XXX
    ingress.kubernetes.io/url-map: k8s2-um-XXX
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: ingress-gw-public-XXX
    networking.gke.io/managed-certificates: XXX,YYY,ZZZ
    networking.gke.io/v1beta1.FrontendConfig: default-frontend-config-XXX
  labels:
    app.kubernetes.io/managed-by: pulumi
  name: gke-ingress-XXX
spec:
  defaultBackend:
    service:
      name: istio-XXX
      port:
        number: 443
  rules:
  - host: '*.example.com'
    http:
      paths:
      - backend:
          service:
            name: istio-XXX
            port:
              number: 443
        path: /*
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - XXX.example.com
    secretName: secret-XXX
  - hosts:
    - YYY.example.com
    secretName: secret-YYY
  - hosts:
    - ZZZ.example.com
    secretName: secret-ZZZ
status:
  loadBalancer:
    ingress:
    - ip: XX.XX.XX.XX
```
